sudo: false
language: java
install:
  - mkdir -p ~/bin
  - export PATH=~/bin:$PATH
  # Could use `latest` tag instead of version number
  - curl -L https://github.com/boot-clj/boot-bin/releases/download/2.5.2/boot.sh -o ~/bin/boot
  - chmod +x ~/bin/boot
deploy:
  skip_cleanup: true
  provider: script
  script: boot deploy
  on:
    tags: true
notifications:
  slack:
    secure: fKB+zUcptEAfaYAsRljIoGS1DMJkux8XbnJeTsmBeKR+IAZPy1qMGEk/BD+eE+RTOx2BpuwU+MhQFd33iW4K/WiRZUvKn8p3YcHi7DIPmU3J/ejUc+O3rzinn+OIUuDPNilaloAeSblEbSI3cK3+UasqPFmzFZUKMbjU4EI9sGXWluYUDBeMcZJ82SyGOXUbx7gGM9xcr10fupEsdTRR6NuVuqRVlL7QDhU2HsJoKlLHQb+bAydevfQ86l7rWBV+ETEvS6+BTgr5dmAz/qG/WuZD0eDo9P8hwp0MdGofuHObsfjfuvE8z9+byt4KzqP66adFy7pQLKullmw+QLGZp4oxl/EAhpuxk6XtQs3kPA20bpGFaup8q03OfF/wYg8CvjZB1lmQHLZn88k+k6P9meDDql+cuNWkU/tuoLxfUBFInfoP+T5K8BBEJcSH9OAjzTMmfdZT5eNN6fArlvP0U7Cj8SJhNJpEE5/ScJzeCE3ytt3vP8pjiy1C9vdbUwCtRbUScLyBzYObUW9LsumsAc3lqbk+lkTsEJvn+flK2z+Gz1SR0plUcjgPEMDTdNBPQLoMas+SmH7zba+xjN8MkA0lfFqLKMJztilykB1OVSRoCtTK2gPx4YuoftGotA60RwnYLtaVaELJJT/byKRqgRd89qeKWz7ypRJuHuU7oTc=
env:
  global:
  - secure: xmKdW2GpRC5P/kkG2vFaMeqx1C/uLFKO4O7El7Fug4ueGpfCbyt933XfGf5cA+BkimEr4Q1I9S5KQyQnyoHs4xiGycb11pXgorstytfw/c1kzWr6EjLNQ0tPi7y7TlwJfCNepHGbsXA1LuU38KX4tSPy8emO6ybvsiO5cX9y0nK9m1sh5R2BxPO8huZT8DT1ypaeeaQ2VDERAf1M44vhdO0sYt9i7S86WciyB9Cr6a/XiX9zskuQsMx0c0clxfarkTffXybTFyTtgP0OUYfuE+rSx12ULnhTuYxjDIgBVXMmmIdi7u0dpLRJSeEwxNyDA7wcN5Un3JZpgaG3/QiqoLdzi0dsd1mU3yXhhWz3GU/8WmsDZqCA/mGLM86C6TCfEVTHRvE56eyte+5KJ7tfCUgyhUaM0di6/t08/fCUnramGR0UzGMGU1HnShiPLUTx8xoi1DPRBLYLhTX5pwpVAhLA+XkUv8nqHXl2hTkot1bdue8u9l599F+PFck0Di86789CXPO5vGwVaAGvyY2VlTXAbWYpjB6XEAFlAw0GQ2TMq3BuRxQZ2Ojp1i5IKhVE5+0Oh773xpQSlytGhC39MIA9KgdZkPLzt386/XaQR2YMKJHE7dsMzNEncTvZNKxkkvwz8wJRvTkLBZ0Kd9VaLCiEY2YHO1E3dbNNNzilnXI=
  - secure: hNFS06y0IizCzceL6uDvJx01UpQl0DxiQ8pBuPTX/oTN2FwM5JXZ7o+m/1gJuQKqnSElR1HhZlEAHWnYZctmvYpMxg89ViIKlaTz32QM3ZP0p+hq1nMUORhQXSotC9hS3qabohd9a6p3mLHG6+rPCZxIiSkXAoGjadtjm9XJpnA+TK5rpTKaG0exukZ02l5lZZVj1J+0XWZdq0QTNrOyWbgjO/NHFuo0/QV7fSwAH8ehKOx0IA+Xmc5uoiCq/dvrBuXEQt68J8zGpjWPKlmKlMuxVsjpCHnkDHXaLg5UXJZld6L2tFUWyVqqzczTFcHafEk/vzMf3lceBDRsXL5zL1qRcvcTv0fV5/UmSwqEDlqlf2DVV50BlOtRR8nwtUG/uE89QZDIpYB3Aruh0BDxOanQXJUxce1V7dK9jKrV3VfvX7xQ3aNd5G3hgyhYjluhhAqOazyFji71QJvFIGeXnB43P4v2HSQMMj8nHtcFb1BidgU2IumpSa2wpL2dj3Z9ZJV9Wmig5OUx/x3w2C3yIoJC4nTGjIyNOx2m1BJISFZe/Lcv97CuOoWwhE9sX370DD6DAcGVL35fbRcUjW6pJO3orxh50lt5C/vqvlOGL0ur1SXsYQ9pENCekRVx3ECn1YjUEVh6jDdH4qeegLh4UJO4QQjnR8k2lG4kjBXAX8I=
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
  - $HOME/.boot/cache/bin
  - $HOME/.boot/cache/lib
  - $HOME/bin